services:
  # PostgreSQL Database
  db:
    image: postgres:14
    container_name: sniff_postgres
    environment:
      POSTGRES_DB: sniff_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Flask Application
  app:
    build: .
    container_name: sniff_app
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@db:5432/sniff_db
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped

  # pgAdmin (optional - for database management via web interface)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sniff_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sniffpittsburgh.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: